---
engines:
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: false
  reek:
    enabled: true
ratings:
  paths:
  - lib/**
  - "**.rb"
exclude_paths:
- tests/**
- stash/**
