---
engines:
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    checks:
      Similar Code:
        enabled: false
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: false
  reek:
    enabled: true
ratings:
  paths:
  - "lib/**"
  - "**.rb"
exclude_paths:
- "test/"
- "stash/"
