---
TooManyStatements:
  enabled: true
  max_statements: 8
DuplicateMethodCall:
  max_calls: 2
FeatureEnvy:
  exclude:
    - "Vool::Compiler"
    - "RubyX::RubyCompiler"
    - "Risc::Interpreter"
    - "Risc::TextWriter"
    - "Arm::Translator"
    - "Vm::ToCode"
TooManyMethods:
  max_methods: 30
  exclude:
    - "Vool::Compiler"
    - "RubyX::RubyCompiler"
    - "Ruby::RubyCompiler"
    - "Risc::Interpreter"
    - "Risc::TextWriter"
    - "Arm::Translator"
    - "Util::List"
UtilityFunction:
  exclude:
    - "Vool::Compiler"
    - "RubyX::RubyCompiler"
    - "Risc::Interpreter"
    - "Risc::TextWriter"
    - "Arm::Translator"
    - "Vm::ToCode"
UncommunicativeMethodName:
  exclude:
    - "Vool::Compiler"
    - "RubyX::RubyCompiler"
    - "Risc::TextWriter"
    - "Risc::Interpreter"
    - "Arm::Translator"
    - "Vm::ToCode"
