---
detectors:
  TooManyStatements:
    enabled: true
    max_statements: 8
  DuplicateMethodCall:
    max_calls: 2
  FeatureEnvy:
    exclude:
      - "RubyX::RubyCompiler"
      - "Risc::Interpreter"
      - "Risc::TextWriter"
      - "Arm::Translator"
  TooManyMethods:
    max_methods: 30
    exclude:
      - "RubyX::RubyCompiler"
      - "Ruby::RubyCompiler"
      - "Risc::Interpreter"
      - "Risc::TextWriter"
      - "Arm::Translator"
      - "Util::List"
  UtilityFunction:
    exclude:
      - "RubyX::RubyCompiler"
      - "Risc::Interpreter"
      - "Risc::TextWriter"
      - "Arm::Translator"
  UncommunicativeMethodName:
    exclude:
      - "RubyX::RubyCompiler"
      - "Risc::TextWriter"
      - "Risc::Interpreter"
      - "Arm::Translator"
exclude_paths:
  - test
  - vendor
  - stash
