language: ruby
sudo: false
cache: bundler
script:
  - CODECLIMATE_REPO_TOKEN=e778c5658e8488a37795ec48f8c6990135f7a2ec35ceadc2e816a4ed1e3f20ab ruby test/test_all.rb
rvm:
  - 2.1.10
  - 2.2.5
  - 2.3.1
